# This is a basic workflow to help you get started with Actions

name: Appwrite Install to Heroku

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Make directory
        run: mkdir appwrite-github \
             -- cd appwite-github
               
      - name: Install Appwrite
        run: docker run -it --rm \
            --volume /var/run/docker.sock:/var/run/docker.sock \
            --volume "$(pwd)"/appwrite:/install/appwrite:rw \
            -e version=0.6.2 \
            appwrite/install 
            
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4.1.5
        with:
          commit_message: Updated files
            
      - name: Docker build the file and publish to Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v2.0.0
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          app_name: ${{ secrets.HEROKU_APP_NAME }} # you application name
          dockerfile_path: './Dockerfile' # set the path to the folder wher the Dokerfile is located
                
